version: "3.8"

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    ports:
      - 8000:8000
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:10
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
