version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:delegated
    ports:
      - 8000:8000
    command: uvicorn src.main:app --host 0.0.0.0 --reload --port 8000
    depends_on:
      db:
        condition: service_healthy

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/app/src:delegated
    command: poetry run python ./src/consumer.py
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:10
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=main
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
