version: "3.8"

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:delegated
    ports:
      - 5000:5000
    command: uvicorn src.main:app --host 0.0.0.0 --reload --port 5000
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./src/consumer.py
    depends_on:
      - db

  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
